version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    command:
      - --save 1 1
    ports:
      - "16379:6379"
    volumes:
      - ./data:/data
